[package]
name = "notes"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
clap = { version = "4.4", features = ["derive"] }
colored = "3.0.0"
dirs = "6.0.0"
crossterm = "0.29.0"
ratatui = "0.29.0"
